Web:
  OnJoin: # This one will be called when the player joins the server
    RequestDescription: "The discord server of fplugins"
    RequestURL: "https://discord.gg/4FF2548"
    Enabled: true

  WebCommands: # This on will be called when the player writes on the command
  - CommandName: "discord"
    RequestDescription: "The discord server of fplugins"
    RequestURL: "https://discord.gg/4FF2548"
    Enabled: true
  - CommandName: "github"
    RequestDescription: "The repository of the plugin"
    RequestURL: "https://github.com/F-Plugins/AdminTools"
    Enabled: true

Broadcast:
  Timer: 500 # Seconds
  RandomOrder: false
  ServiceEnabled: true
  Messages:
  - ImageURL: "https://images-ext-1.discordapp.net/external/1Vg3rH_5wKUid81LpNF3YTOgl-x1Vvix0sNvfrhbtpE/https/unturneditems.com/media/253.png"
    Message: "Announce by FPlugins"
  - ImageURL: "https://images-ext-1.discordapp.net/external/1Vg3rH_5wKUid81LpNF3YTOgl-x1Vvix0sNvfrhbtpE/https/unturneditems.com/media/253.png"
    Message: "{color=yellow}Just another announce{/color}"