Web:
  OnJoin:
    RequestDescription: "The discord server of F-Plugins"
    RequestURL: "https://discord.gg/4FF2548"
    Enabled: false
  WebCommands:
  - CommandName: "discord"
    RequestDescription: "The discord server of F-Plugins"
    RequestURL: "https://discord.gg/4FF2548"
    Enabled: false
  - CommandName: "github"
    RequestDescription: "The repository of the plugin"
    RequestURL: "https://github.com/F-Plugins/AdminTools"
    Enabled: false
Broadcast:
  Timer: 600
  RandomOrder: false
  ServiceEnabled: false
  Messages:
  - ImageURL: "https://images-ext-1.discordapp.net/external/1Vg3rH_5wKUid81LpNF3YTOgl-x1Vvix0sNvfrhbtpE/https/unturneditems.com/media/253.png"
    Message: "Announce by FPlugins"
  - ImageURL: "https://images-ext-1.discordapp.net/external/1Vg3rH_5wKUid81LpNF3YTOgl-x1Vvix0sNvfrhbtpE/https/unturneditems.com/media/253.png"
    Message: "{color=yellow}Just another announce{/color}"
Restrictions:
  Items:
  - Ids:
    - 0
    BypassPermission: "bypass.default"
  Vehicles:
  - Ids:
    - 186
    - 187
    BypassPermission: "bypass.deafult"
